<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-17T07:45:03Z" name="Default suite" finished-at="2024-06-17T07:45:11Z" duration-ms="7914">
    <groups>
    </groups>
    <test started-at="2024-06-17T07:45:03Z" name="Default test" finished-at="2024-06-17T07:45:11Z" duration-ms="7914">
      <class name="Automation_Testing.UI_TestNG">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:03Z" name="beforeSuite" finished-at="2024-06-17T07:45:03Z" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:03Z" name="beforeTest" finished-at="2024-06-17T07:45:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:03Z" name="beforeClass" finished-at="2024-06-17T07:45:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="validateLaunchOfTestPlayground()[pri:1, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:03Z" name="validateLaunchOfTestPlayground" finished-at="2024-06-17T07:45:10Z" duration-ms="7447" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [UI Test Automatio Playgroun] but found [UI Test Automation Playground]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [UI Test Automatio Playgroun] but found [UI Test Automation Playground]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Automation_Testing.UI_TestNG.validateLaunchOfTestPlayground(UI_TestNG.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLaunchOfTestPlayground -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:03Z" name="beforeMethod" finished-at="2024-06-17T07:45:03Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:10Z" name="afterMethod" finished-at="2024-06-17T07:45:10Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="validateResources()[pri:2, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:10Z" name="validateResources" finished-at="2024-06-17T07:45:10Z" depends-on-methods="Automation_Testing.UI_TestNG.validateLaunchOfTestPlayground" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method UI_TestNG.validateResources()[pri:2, instance:Automation_Testing.UI_TestNG@26abb146] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method UI_TestNG.validateResources()[pri:2, instance:Automation_Testing.UI_TestNG@26abb146] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateResources -->
        <test-method signature="validateDevhints()[pri:3, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:10Z" name="validateDevhints" finished-at="2024-06-17T07:45:10Z" depends-on-methods="Automation_Testing.UI_TestNG.validateLaunchOfTestPlayground, Automation_Testing.UI_TestNG.validateResources" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method UI_TestNG.validateDevhints()[pri:3, instance:Automation_Testing.UI_TestNG@26abb146] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method UI_TestNG.validateDevhints()[pri:3, instance:Automation_Testing.UI_TestNG@26abb146] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDevhints -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:10Z" name="afterClass" finished-at="2024-06-17T07:45:11Z" duration-ms="420" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:11Z" name="afterTest" finished-at="2024-06-17T07:45:11Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:Automation_Testing.UI_TestNG@26abb146]" started-at="2024-06-17T07:45:11Z" name="afterSuite" finished-at="2024-06-17T07:45:11Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- Automation_Testing.UI_TestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
